# Local build of the production Dockerfile

networks:
  jellyfin_htpc:
    external: true

services:
  discovarr-qa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discovarr-qa
    ports:
      - "8000:8000"  # FastAPI backend dev server (using host port 8001 to avoid conflicts)
    environment:
      # Common environment variables
      - LOGLEVEL=DEBUG
      - TZ=America/Denver
      # Client needs to know where the API is (exposed on host port 8001)
      - VITE_DISCOVARR_URL=http://192.168.0.100:8001/api

      # Backend API Keys and URLs (copy from your existing discovarr-api or discovarr service)
      - JELLYFIN_URL=http://jellyfin:8096
      - JELLYFIN_API_KEY=
      - GEMINI_API_KEY= # NO DOUBLE QUOTES
      - GEMINI_MODEL=gemini-2.5-flash-preview-04-17
      - RADARR_URL=http://radarr:7878
      - RADARR_API_KEY=
      - SONARR_URL=http://sonarr:8989
      - SONARR_API_KEY=
      - TMDB_API_KEY=
    networks:
      - jellyfin_htpc # Ensure this network is defined or external as in your example
    restart: unless-stopped # Or 'no' for typical dev workflows